# Generated by Django 4.1.4 on 2022-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='are_you_doctor',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
