# Generated by Django 4.1.4 on 2022-12-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_are_you_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='Location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='add',
            name='phone',
        ),
    ]
