# Generated by Django 4.1.4 on 2022-12-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_test_delete_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
