# Generated by Django 4.1.4 on 2022-12-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_test_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
