# Generated by Django 4.1.4 on 2022-12-12 20:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0008_test_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Add',
        ),
    ]
