# Generated by Django 4.1.4 on 2022-12-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
    ]
